---
openshift_master_identity_providers:
  - name: htpasswd_auth
    login: 'true'
    challenge: 'true'
    kind: HTPasswdPasswordIdentityProvider
openshift_master_default_subdomain: apps.jamesjonesconsulting.com