vip_ip_address: 192.168.1.110
vip_router_id: 10
default_keepalived_vip: VI_1
keepalived_vips:
  VI_1:
    address: 192.168.1.110
    router_id: 10
  OKD_1:
    address: 192.133.0.128
    router_id: 11
vip_router: nginx
vip_router_package: nginx
vip_consul_confs:
  - consul-ui
  - nomad-ui
  - cms
vip_consul_streams: []
vip_consul_san_certs:
  - apps.jamesjonesconsulting.com
  - jamesjonesconsulting.com
  - apps.okd.jamesjonesconsulting.com
  - okd.jamesjonesconsulting.com
