---
ansible_user: jam
ansible_host: 192.168.1.29
gitlab_runner_host_tags:
  - small-build
gitlab_runner_host_count: 3
gitlab_runner_host_run_untagged: true
vsts_host_agents:
  - pool: FedoraHosted
    name: beebox_1
    folder: FedoraHosted/beebox_1
    username: jam
  - pool: FedoraHosted
    name: beebox_2
    folder: FedoraHosted/beebox_2
    username: jam
  - pool: FedoraHosted
    name: beebox_3
    folder: FedoraHosted/beebox_3
    username: jam
github_actions_host_agents:
  - name: beebox_1
    username: jam
  - name: beebox_2
    username: jam
  - name: beebox_3
    username: jam
