---
ansible_user: jam
ansible_host: 192.168.1.19
gitlab_runner_host_tags:
  - small-build
gitlab_runner_host_count: 3
gitlab_runner_host_run_untagged: true
vsts_host_agents:
  - pool: FedoraHosted
    name: build03_1
    folder: FedoraHosted/build03_1
    username: jam
  - pool: FedoraHosted
    name: build03_2
    folder: FedoraHosted/build03_2
    username: jam
  - pool: FedoraHosted
    name: build03_3
    folder: FedoraHosted/build03_3
    username: jam
github_actions_host_agents:
  - name: build03_1
    username: jam
  - name: build03_2
    username: jam
  - name: build03_3
    username: jam
salt_master: build01.jamesjonesconsulting.com
salt_states:
  - cockpit
