---
ansible_user: jam
ansible_host: 192.168.1.54
gitlab_runner_host_tags:
  - big-build
gitlab_runner_host_count: 3
gitlab_runner_host_run_untagged: true
vsts_host_agents:
  - pool: FedoraHosted
    name: eglobalr9_1
    folder: FedoraHosted/eglobalr9_1
    username: jam
  - pool: FedoraHosted
    name: eglobalr9_2
    folder: FedoraHosted/eglobalr9_2
    username: jam
  - pool: FedoraHosted
    name: eglobalr9_3
    folder: FedoraHosted/eglobalr9_3
    username: jam
github_actions_host_agents:
  - name: eglobalr9_1
    username: jam
  - name: eglobalr9_2
    username: jam
  - name: eglobalr9_3
    username: jam
salt_master: build01.jamesjonesconsulting.com
salt_states:
  - cockpit
