---
ansible_user: jam
ansible_host: 192.168.1.31
gitlab_runner_host_tags:
  - small-build
gitlab_runner_host_count: 3
gitlab_runner_host_run_untagged: true
vsts_host_agents:
  - pool: FedoraHosted
    name: jamacer_1
    folder: FedoraHosted/jamacer_1
    username: jam
  - pool: FedoraHosted
    name: jamacer_2
    folder: FedoraHosted/jamacer_2
    username: jam
  - pool: FedoraHosted
    name: jamacer_3
    folder: FedoraHosted/jamacer_3
    username: jam
github_actions_host_agents:
  - name: jamacer_1
    username: jam
  - name: jamacer_2
    username: jam
  - name: jamacer_3
    username: jam




