---
ansible_user: jam
ansible_host: 192.168.1.42
gitlab_runner_host_tags:
  - small-build
gitlab_runner_host_count: 3
gitlab_runner_host_run_untagged: true
vsts_host_agents:
  - pool: FedoraHosted
    name: jamtv_1
    folder: FedoraHosted/jamtv_1
    username: jam
  - pool: FedoraHosted
    name: jamtv_2
    folder: FedoraHosted/jamtv_2
    username: jam
  - pool: FedoraHosted
    name: jamtv_3
    folder: FedoraHosted/jamtv_3
    username: jam
github_actions_host_agents:
  - name: jamtv_1
    username: jam
  - name: jamtv_2
    username: jam
  - name: jamtv_3
    username: jam
salt_master: build01.jamesjonesconsulting.com
salt_states:
  - cockpit




