---
ansible_user: jam
ansible_host: 192.168.1.19
gitlab_runner_host_tags:
  - big-build
gitlab_runner_host_count: 7
gitlab_runner_host_run_untagged: true
vsts_host_agents:
  - pool: FedoraHosted
    name: music_1
    folder: FedoraHosted/jambrix_1
    username: jam
  - pool: FedoraHosted
    name: music_2
    folder: FedoraHosted/jambrix_2
    username: jam
  - pool: FedoraHosted
    name: music_3
    folder: FedoraHosted/jambrix_3
    username: jam
github_actions_host_agents:
  - name: music_1
    username: jam
  - name: music_2
    username: jam
  - name: music_3
    username: jam
salt_master: build01.jamesjonesconsulting.com
salt_states:
  - cockpit
